{{- if eq (include "tuleap.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tuleap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tuleap.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  tuleap-sys-db-password: {{ include "tuleap.sys.db.password" . | b64enc | quote }}
  tuleap-site-admin-password: {{ include "tuleap.site.admin.password" . | b64enc | quote }}
{{- end }}
